version: "3.5"
services:
  haproxy:
    container_name: ${COMPOSE_PROJECT_NAME}_haproxy
    hostname: ${COMPOSE_PROJECT_NAME}_haproxy
    image: haproxy:latest
    volumes:
      - "./data/haproxy/etc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      # mysql to proxysql
      - "3306:3306"
      # haproxy stats
      - "6081:6081"
    depends_on:
      - "proxysql02"

  proxysql01:
    container_name: ${COMPOSE_PROJECT_NAME}_proxysql01
    hostname: ${COMPOSE_PROJECT_NAME}_proxysql01
    image: percona/proxysql2
    volumes:
      - "./data/proxysql/etc/proxysql/proxysql.cnf:/etc/proxysql/proxysql.cnf"
      - "./data/proxysql/etc/proxysql-admin.cnf:/etc/proxysql-admin.cnf"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      # proxysql admin interface
      - "6032:6032"
      # proxysql web interface
      - "6091:6080"
    depends_on:
      - "db03"

  proxysql02:
    container_name: ${COMPOSE_PROJECT_NAME}_proxysql02
    hostname: ${COMPOSE_PROJECT_NAME}_proxysql02
    image: percona/proxysql2
    volumes:
      - "./data/proxysql/etc/proxysql/proxysql.cnf:/etc/proxysql/proxysql.cnf"
      - "./data/proxysql/etc/proxysql-admin.cnf:/etc/proxysql-admin.cnf"
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      # proxysql admin interface
      - "6033:6032"
      # proxysql web interface
      - "6092:6080"
    depends_on:
      - "proxysql01"

  db01:
    container_name: ${COMPOSE_PROJECT_NAME}_db01
    hostname: ${COMPOSE_PROJECT_NAME}_db01
    image: percona/percona-xtradb-cluster:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      XTRABACKUP_PASSWORD: Password123
      CLUSTER_NAME: cluster01
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    volumes:
      # mysql init DB and users
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
        test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'show databases'"

  db02:
    container_name: ${COMPOSE_PROJECT_NAME}_db02
    hostname: ${COMPOSE_PROJECT_NAME}_db02
    image: percona/percona-xtradb-cluster:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      XTRABACKUP_PASSWORD: Password123
      CLUSTER_NAME: cluster01
      CLUSTER_JOIN: db01
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
        test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'show databases'"
    depends_on:
      db01:
          condition: service_healthy

  db03:
    container_name: ${COMPOSE_PROJECT_NAME}_db03
    hostname: ${COMPOSE_PROJECT_NAME}_db03
    image: percona/percona-xtradb-cluster:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      XTRABACKUP_PASSWORD: Password123
      CLUSTER_NAME: cluster01
      CLUSTER_JOIN: db01
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3309:3306'
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      db02:
          condition: service_healthy

  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    environment:
      ADMINER_DEFAULT_SERVER: haproxy
    ports:
      - '8081:8080'
    volumes:
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "proxysql02"
